name: Build with Make

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run make
        run: make
      - name: Get Version number
        id: get-package-version
        run: node .github/version.cjs
      - name: Upload Firefox
        uses: actions/upload-artifact@v4
        with:
          name: firefox_UNSIGNED-${{ steps.get-package-version.outputs.version }}-${{github.sha}}.zip
          path: dist/*anti-doomscroll.*
          if-no-files-found: error

      - name: Upload Chrome xpi
        uses: actions/upload-artifact@v4
        with:
          name: CHROME_anti-doomscroll_UNSIGNED-${{ steps.get-package-version.outputs.version }}-${{github.sha}}.zip
          path: dist-chrome/*anti-doomscroll.*
          if-no-files-found: error

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
      - name: Run Lints
        run: yarn check
      - name: "web-ext lint"
        uses: kewisch/action-web-ext@v1
        with:
          cmd: lint
          source: dist
          channel: listed
      - name: "web-ext lint (chrome)"
        uses: kewisch/action-web-ext@v1
        with:
          cmd: lint
          source: dist-chrome
          channel: listed
